version = 0.1
[default.deploy.parameters]
stack_name = "sam-demo-2"
resolve_s3 = true
s3_prefix = "sam-demo-2"
region = "eu-west-1"
profile = "Husny-Admin-x"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
